services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-interview-backend

    env_file:
      - .env

    environment:
      DATABASE_URL: sqlite:////app/data/interview.db

    volumes:
      - interview_data:/app/data

    ports:
      - "8000:8000"

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: ai-interview-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped


volumes:
  interview_data: